---
name: Tautulli
version: dev
slug: tautulli
description: Monitoring and tracking tool for Plex Media Server
url: https://github.com/hassio-addons/addon-tautulli/tree/main/README.md
webui: "[PROTO:ssl]://[HOST]:[PORT:8181]"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
hassio_api: true
ports:
  8181/tcp: 8181
ports_description:
  8181/tcp: Tautulli web interface
map:
  - ssl
  - share:rw
options:
  username: ""
  password: ""
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  username: str
  password: password
  ssl: bool
  certfile: str
  keyfile: str
  leave_front_door_open: bool?
