#!/usr/bin/with-contenv bash
# ==============================================================================
# Community Hass.io Add-ons: Tautulli
# Runs the NGINX daemon
# ==============================================================================
# shellcheck disable=SC1091
source /usr/lib/hassio-addons/base.sh

# Wait for Tautulli to become available
s6-svwait -u -t 5000 /var/run/s6/services/tautulli

hass.log.info "Starting NGINX..."
exec nginx -g "daemon off;"
